/*
THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF PARALLAX
SOFTWARE CORPORATION ("PARALLAX").  PARALLAX, IN DISTRIBUTING THE CODE TO
END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
COPYRIGHT 1993-1998 PARALLAX SOFTWARE CORPORATION.  ALL RIGHTS RESERVED.
*/
/*
 * $Source: Buggin:miner:source:3d::RCS:horizon.c $
 * $Revision: 1.1 $
 * $Author: allender $
 * $Date: 1995/05/05 08:51:14 $
 *
 * Horizon drawer
 *
 * $Log: horizon.c $
 * Revision 1.1  1995/05/05  08:51:14  allender
 * Initial revision
 *
 * Revision 1.1  1995/04/17  06:38:57  matt
 * Initial revision
 *
 *
 */

#include "3d/3d.h"

//draw a horizon
void g3_draw_horizon(int sky_color, int ground_color)
{
	//[ISB] crackets dadadadadadaaa. crackets dadadadadadaaa.
}
