// 
// Auto-generated include file 
// Generated by MAKE from INFERNO.INI settings 
// 

#pragma once //[ISB] this file was bad idea

#define NEWDEMO				//Demo is always IN 
//#define EDITOR				//BUILD_EDITOR not set 
//#define SHAREWARE				//SHAREWARE not set 
#define SANTA				//SANTA set //[ISB] it looks like SANTA came early this year.
//#define ARCADE				//ARCADE not set 
//#define DEMO_ONLY				//DEMO_ONLY not set 
//#define _MARK_ON				//MARK_ON not set 
//#define PASSWORD				//PASSWORD not set 
//#define STORE_DEMO				//STORE_DEMO not set 
//#define D2_OEM				//D2_OEM not set 
//#define COMPILATION				//COMPILATION not set 
//#define SATURN				//SATURN not set 
//#define COMPACT_SEGS				//COMPACT_SEGS not set 
//#define NOSERIAL				//NOSERIAL not set 
//#define NETWORK 1				//NO_MULTIPLAYER not set  
#define PIGGY_USE_PAGING 1				//PIGGY_NO_PAGING not set  
